name:           rg
version:        1.4.0.0
github:         "cdornan/rg"
license:        BSD3
author:         "Chris Dornan"
maintainer:     "chris.dornan@irisconnect.co.uk"
copyright:      "2019 Chris Dornan"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:       A dynamic/unbounded alternative to Bounded Enum
category:       Types

description:    Please see the README on GitHub at <https://github.com/cdornan/rg#readme>

dependencies:
- base                  >= 4.8 && < 5
- array
- fmt                   >= 0.4.0.0
- possibly
- text                  >= 1.2
- unordered-containers  >= 0.2.0.0
- vector                >= 0.11.0.0

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  nike-test:
    main:                test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - rg
    - tasty
    - tasty-hunit
